version: '2.2'
services:
  scheduler:
    image: "askyora/common:ep-status"
    environment:
     - GRID_URL=http://firefox:4444/wd/hub
     - SPRING_MAIL_PASSWORD=XXX
     - SPRING_MAIL_USERNAME=XXX
     - NAME=XXX
     - DOB=DD/MM/YYYY
     - FIN=XXXXXXXXX
     - PASSPORT=XXXXXXXX
     - FROM=XXXXXX
     - TO=XXXXXXX
     - AM_HOUR=9
     - AM_MINUTES=0
     - JOB_TIMEZONE=IST
    depends_on:
     - firefox
  firefox:
    image: "selenium/standalone-firefox-debug"
    ports:
     - "4444:4444"
    environment:
     - no_proxy=localhost
